### ISSUE TITLE
spurious docker files

### ISSUE THREAD

**Issue by bdarcus** [FreekMencke/node-ts-starter-cli#4]
Thanks for this!

One little thing. This:

```console
❯ npx node-ts-starter-cli create csl-next-ts -g -l -p
```

... creates docker files also (`Dockerfile` and `.dockerignore`).

**Comment by FreekMencke** [comment]
I think that the following lines are a copy paste mistake that cause this, they shouldn't be in the github-action part. 

https://github.com/FreekMencke/node-ts-starter-cli/blob/c202165c2884677491db9ec0ec1f382be65b20a2/src/create.js#L112-L115

I'll probably fix this in the weekend, thanks for logging it.

**Comment by FreekMencke** [comment]
Be sure to use `npx node-ts-starter-cli@latest` or `npx node-ts-starter-cli@0.2.5`.

**Comment by bdarcus** [comment]
Thanks!

I ended up using the output to adapt to [my package](https://github.com/bdarcus/csl-next.js/blob/main/package.json). I'm using `rome` there, in place of `prettier` and `eslint`, for example, and native node test runner.

I'm an amateur programmer, and a typescript/node/js newbie, so need all the help I can get!
