### ISSUE TITLE
swagger has errors

### ISSUE THREAD

**Issue by josersleal** [FreekMencke/node-ts-starter-cli#5]
errors:

Version is mandatory in Info object(http://a.ml/vocabularies/amf/parser#mandatory-api-version)
Info object 'title' must be a single value(http://a.ml/vocabularies/amf/parser#WebAPI-name-minCount)
Error reading file "file:///e%3A/Projects/spike/node-ts/ntas-cli-2/swagger/src/swagger/src/info/index.yaml: cannot open file:///e%3A/Projects/spike/node-ts/ntas-cli-2/swagger/src/swagger/src/info/index.yaml. Detail: Unable to read file 'e:\Projects\spike\node-ts\ntas-cli-2\swagger\src\swagger\src\info\index.yaml' (Error: Unable to resolve nonexistent file 'e:\Projects\spike\node-ts\ntas-cli-2\swagger\src\swagger\src\info\index.yaml')"
File Not Found: ENOENT: no such file or directory, open 'e:\Projects\spike\node-ts\ntas-cli-2\swagger\src\swagger\src\info\index.yaml'(http://a.ml/vocabularies/amf/core#unresolved-reference)
Top level element describing a HTTP API

**Comment by FreekMencke** [comment]
I'm not sure why you would post a swagger error here. This project is a cli that creates a node.js project with esbuild. If anything, your problem would be with esbuild, and not with this cli. I'm going to close this issue. I don't know what you expect me to do when you only post a swagger error, without any context whatsoever.

**Comment by josersleal** [comment]
The  context is the default generation of openapi files.
If the tool you use is not working, I thought you would like to know so to remove or replace. Good work otherwise,
